#server.port= 8084
#spring.jpa.defer-datasource-initialization= true
#spring.datasource.url= jdbc:oracle:thin:@localhost:1521:xe

#DataBase Related Properties
#oracle.driver.class= oracle.jdbc.OracleDriver
#oracle.database.username= system
#oracle.database.password = manager

#vault related properties
spring.cloud.vault.scheme= http
spring.cloud.vault.authentication=token
spring.cloud.vault.host= localhost
spring.cloud.vault.port= 8200
spring.cloud.vault.token= hvs.zcluzq9YRJI6W5ehaj2NbPmo
spring.cloud.vault.paths= secret/oracleSecret
#logging.level.org.springframework.context.annotation= DEBUG


#liquibase related configuration
spring.liquibase.changeLog= classpath:db/migration/master-change-log.xml
#spring.main.web-application-type= none

#to create diningTable automatically using jpa functionality
#spring.jpa.hibernate.ddl-auto = update

spring.datasource.url=jdbc:h2:file:./src/main/resources/db-files/h2-files
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update
server.port=9090


# jwt changes
teams.app.jwtSecret= L3TQ2xDP4DJDq7+6zMmrVm0T5VjYFg0zM+Nhc5Mx+YY=
teams.app.jwtExpirationMs= 86400000
